site_name: holdtheline
site_description: Do you have the heart of the cards?
repo_url: https://github.com/scottcmorris/holdtheline
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/scottcmorris">scottcmorris</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
