# Generated by Django 2.1.7 on 2019-03-15 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.PositiveSmallIntegerField(choices=[(0, 'Green'), (1, 'Red'), (2, 'Orange'), (3, 'Blue'), (4, 'Yellow'), (5, 'Purple')])),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='CardLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.SmallIntegerField(choices=[(0, 'Deck'), (1, 'Player 1'), (2, 'Player 2'), (3, 'Player 3'), (4, 'Player 4'), (5, 'Lane: 1, Side: Bottom, Slot: 1'), (6, 'Lane: 1, Side: Bottom, Slot: 2'), (7, 'Lane: 1, Side: Bottom, Slot: 3'), (8, 'Lane: 1, Side: Top, Slot: 1'), (9, 'Lane: 1, Side: Top, Slot: 2'), (10, 'Lane: 1, Side: Top, Slot: 3'), (11, 'Lane: 2, Side: Bottom, Slot: 1'), (12, 'Lane: 2, Side: Bottom, Slot: 2'), (13, 'Lane: 2, Side: Bottom, Slot: 3'), (14, 'Lane: 2, Side: Top, Slot: 1'), (15, 'Lane: 2, Side: Top, Slot: 2'), (16, 'Lane: 2, Side: Top, Slot: 3'), (17, 'Lane: 3, Side: Bottom, Slot: 1'), (18, 'Lane: 3, Side: Bottom, Slot: 2'), (19, 'Lane: 3, Side: Bottom, Slot: 3'), (20, 'Lane: 3, Side: Top, Slot: 1'), (21, 'Lane: 3, Side: Top, Slot: 2'), (22, 'Lane: 3, Side: Top, Slot: 3'), (23, 'Lane: 4, Side: Bottom, Slot: 1'), (24, 'Lane: 4, Side: Bottom, Slot: 2'), (25, 'Lane: 4, Side: Bottom, Slot: 3'), (26, 'Lane: 4, Side: Top, Slot: 1'), (27, 'Lane: 4, Side: Top, Slot: 2'), (28, 'Lane: 4, Side: Top, Slot: 3'), (29, 'Lane: 5, Side: Bottom, Slot: 1'), (30, 'Lane: 5, Side: Bottom, Slot: 2'), (31, 'Lane: 5, Side: Bottom, Slot: 3'), (32, 'Lane: 5, Side: Top, Slot: 1'), (33, 'Lane: 5, Side: Top, Slot: 2'), (34, 'Lane: 5, Side: Top, Slot: 3'), (35, 'Lane: 6, Side: Bottom, Slot: 1'), (36, 'Lane: 6, Side: Bottom, Slot: 2'), (37, 'Lane: 6, Side: Bottom, Slot: 3'), (38, 'Lane: 6, Side: Top, Slot: 1'), (39, 'Lane: 6, Side: Top, Slot: 2'), (40, 'Lane: 6, Side: Top, Slot: 3'), (41, 'Lane: 7, Side: Bottom, Slot: 1'), (42, 'Lane: 7, Side: Bottom, Slot: 2'), (43, 'Lane: 7, Side: Bottom, Slot: 3'), (44, 'Lane: 7, Side: Top, Slot: 1'), (45, 'Lane: 7, Side: Top, Slot: 2'), (46, 'Lane: 7, Side: Top, Slot: 3'), (47, 'Lane: 8, Side: Bottom, Slot: 1'), (48, 'Lane: 8, Side: Bottom, Slot: 2'), (49, 'Lane: 8, Side: Bottom, Slot: 3'), (50, 'Lane: 8, Side: Top, Slot: 1'), (51, 'Lane: 8, Side: Top, Slot: 2'), (52, 'Lane: 8, Side: Top, Slot: 3'), (53, 'Lane: 9, Side: Bottom, Slot: 1'), (54, 'Lane: 9, Side: Bottom, Slot: 2'), (55, 'Lane: 9, Side: Bottom, Slot: 3'), (56, 'Lane: 9, Side: Top, Slot: 1'), (57, 'Lane: 9, Side: Top, Slot: 2'), (58, 'Lane: 9, Side: Top, Slot: 3')])),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
                ('won', models.SmallIntegerField(choices=[(-1, 'Bottom'), (0, 'Unclaimed'), (1, 'Top')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15)),
            ],
        ),
    ]
