# Generated by Django 2.1.7 on 2019-03-17 20:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.PositiveSmallIntegerField(choices=[(0, 'Green'), (1, 'Red'), (2, 'Orange'), (3, 'Blue'), (4, 'Yellow'), (5, 'Purple')])),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ('color', 'value'),
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card1', to='game.Card')),
                ('card2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card2', to='game.Card')),
                ('card3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card3', to='game.Card')),
                ('card4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card4', to='game.Card')),
                ('card5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card5', to='game.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.SmallIntegerField(choices=[(-1, 'Bottom'), (0, 'Unclaimed'), (1, 'Top')], default=0)),
                ('bot1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot1', to='game.Card')),
                ('bot2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot2', to='game.Card')),
                ('bot3', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot3', to='game.Card')),
                ('top1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top1', to='game.Card')),
                ('top2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top2', to='game.Card')),
                ('top3', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top3', to='game.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Lanes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane1', to='game.Lane')),
                ('lane2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane2', to='game.Lane')),
                ('lane3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane3', to='game.Lane')),
                ('lane4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane4', to='game.Lane')),
                ('lane5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane5', to='game.Lane')),
                ('lane6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane6', to='game.Lane')),
                ('lane7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane7', to='game.Lane')),
                ('lane8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane8', to='game.Lane')),
                ('lane9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane9', to='game.Lane')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.AddField(
            model_name='hand',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='lanes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Lanes'),
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='game.Player'),
        ),
        migrations.AddField(
            model_name='deck',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('color', 'value')},
        ),
    ]
