# Generated by Django 2.1.7 on 2019-03-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190317_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='game',
        ),
        migrations.AddField(
            model_name='deck',
            name='game_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='game_id', to='game.Game'),
        ),
        migrations.AddField(
            model_name='deck',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.ManyToManyField(to='game.Deck'),
        ),
        migrations.AddField(
            model_name='game',
            name='hand1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand1', to='game.Hand'),
        ),
        migrations.AddField(
            model_name='game',
            name='hand2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand2', to='game.Hand'),
        ),
        migrations.AddField(
            model_name='game',
            name='hand3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand3', to='game.Hand'),
        ),
        migrations.AddField(
            model_name='game',
            name='hand4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand4', to='game.Hand'),
        ),
    ]
