# Generated by Django 2.1.7 on 2019-03-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190319_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='game_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='game_id', to='game.Game'),
        ),
    ]
