# Generated by Django 2.1.7 on 2019-03-16 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190316_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
    ]
