# Generated by Django 2.1.7 on 2019-03-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190319_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='game_id',
            new_name='game_fk',
        ),
    ]
