# Generated by Django 2.1.7 on 2019-03-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190319_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hand',
            old_name='game',
            new_name='game_fk',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='player',
            new_name='player_fk',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='card1',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='card2',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='card3',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='card4',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='card5',
        ),
        migrations.AddField(
            model_name='hand',
            name='card_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Card'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='hand1',
        ),
        migrations.AddField(
            model_name='game',
            name='hand1',
            field=models.ManyToManyField(related_name='hand1', to='game.Hand'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='hand2',
        ),
        migrations.AddField(
            model_name='game',
            name='hand2',
            field=models.ManyToManyField(related_name='hand2', to='game.Hand'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='hand3',
        ),
        migrations.AddField(
            model_name='game',
            name='hand3',
            field=models.ManyToManyField(related_name='hand3', to='game.Hand'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='hand4',
        ),
        migrations.AddField(
            model_name='game',
            name='hand4',
            field=models.ManyToManyField(related_name='hand4', to='game.Hand'),
        ),
    ]
